services:
  - type: web
    name: smart-attendance-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_SECRET_KEY
        sync: false
      - key: ALLOWED_IP_PREFIXES
        sync: false
      - key: SKIP_TIME_CHECK
        value: false
      - key: ENTRY_START
        value: "06:00"
      - key: ENTRY_END
        value: "09:30"
      - key: EXIT_START
        value: "16:00"
      - key: EXIT_END
        value: "20:00"
      - key: FRONTEND_URL
        sync: false
